# -*- coding: utf-8 -*-
"""N9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z9UCRpeVr0kh_S9AbZtofV6scx1H-Zn6
"""

def longestPalSubstr(string):
    maxLength = 1
    start = 0
    length = len(string)
    low = 0
    high = 0
    for i in range(1, length):
        low = i - 1
        high = i
        while low >= 0 and high < length and string[low] == string[high]:
            if high - low + 1 > maxLength:
                start = low
                maxLength = high - low + 1
            low -= 1
            high += 1

        low = i - 1
        high = i + 1
        while (low >= 0) and (high < length) and (string[low] == string[high]):
            if high - low + 1 > maxLength:
                start = low
                maxLength = high - low + 1
            low -= 1
            high += 1
    print (maxLength, string[start:start + maxLength])
try:
    string = input()
    longestPalSubstr(string)
except EOFError:
    print(0)